-- Skaffa frö-ingredienser (home_id NULL = frö, ägs av Skaffa).
-- Kör EFTER skaffa_schema.sql.
--
-- diet_tag: 'kott' | 'fisk' | null. NULL betyder neutral, inte "vegetariskt" –
-- ett recept blir vegetariskt genom att sakna kött- och fiskmarkerade
-- ingredienser, inte genom att någon ingrediens säger att det är det.
-- Kolumnen är medvetet skild från category: category är butikshyllan, och där
-- ligger Hönsbuljongtärning och Kalvfond under 'grains' bland torrvarorna.
--
-- Idempotent OCH självkorrigerande: konflikt på (home_id, lower(trim(name)))
-- skriver om diet_tag. Kör om filen efter en ändring i listan nedan så rättas
-- befintliga rader. (Fungerar tack vare NULLS NOT DISTINCT på unika indexet –
-- utan det vore varje frörad unik eftersom home_id är NULL, och ingen konflikt
-- hade upptäckts alls.)
insert into ingredients (home_id, name, unit, category, diet_tag) values
  -- ---- produce -------------------------------------------------------------
  (null, 'Gul lök', 'styck', 'produce', null),
  (null, 'Röd lök', 'styck', 'produce', null),
  (null, 'Schalottenlök', 'styck', 'produce', null),
  (null, 'Purjolök', 'styck', 'produce', null),
  (null, 'Vitlök', 'styck', 'produce', null),
  (null, 'Vitlöksklyfta', 'styck', 'produce', null),
  (null, 'Morot', 'styck', 'produce', null),
  (null, 'Palsternacka', 'styck', 'produce', null),
  (null, 'Rödbeta', 'styck', 'produce', null),
  (null, 'Potatis', 'gram', 'produce', null),
  (null, 'Sötpotatis', 'styck', 'produce', null),
  (null, 'Broccoli', 'styck', 'produce', null),
  (null, 'Blomkål', 'styck', 'produce', null),
  (null, 'Vitkål', 'gram', 'produce', null),
  (null, 'Rödkål', 'gram', 'produce', null),
  (null, 'Spetskål', 'styck', 'produce', null),
  (null, 'Grönkål', 'gram', 'produce', null),
  (null, 'Brysselkål', 'gram', 'produce', null),
  (null, 'Zucchini', 'styck', 'produce', null),
  (null, 'Aubergine', 'styck', 'produce', null),
  (null, 'Gurka', 'styck', 'produce', null),
  (null, 'Paprika', 'styck', 'produce', null),
  (null, 'Tomat', 'styck', 'produce', null),
  (null, 'Körsbärstomater', 'gram', 'produce', null),
  (null, 'Champinjoner', 'gram', 'produce', null),
  (null, 'Svamp', 'gram', 'produce', null),
  (null, 'Kantareller', 'gram', 'produce', null),
  (null, 'Sparris', 'gram', 'produce', null),
  (null, 'Haricots verts', 'gram', 'produce', null),
  (null, 'Sockerärter', 'gram', 'produce', null),
  (null, 'Majskolv', 'styck', 'produce', null),
  (null, 'Babyspenat', 'gram', 'produce', null),
  (null, 'Spenat', 'gram', 'produce', null),
  (null, 'Ruccola', 'gram', 'produce', null),
  (null, 'Isbergssallad', 'styck', 'produce', null),
  (null, 'Romansallad', 'styck', 'produce', null),
  (null, 'Stjälkselleri', 'styck', 'produce', null),
  (null, 'Rotselleri', 'styck', 'produce', null),
  (null, 'Fänkål', 'styck', 'produce', null),
  (null, 'Färsk ingefära', 'gram', 'produce', null),
  (null, 'Pumpa', 'gram', 'produce', null),
  (null, 'Rädisor', 'gram', 'produce', null),
  (null, 'Avokado', 'styck', 'produce', null),
  (null, 'Röd chili', 'styck', 'produce', null),
  (null, 'Salladslök', 'styck', 'produce', null),
  (null, 'Färsk dill', 'styck', 'produce', null),
  (null, 'Färsk persilja', 'styck', 'produce', null),
  (null, 'Färsk basilika', 'styck', 'produce', null),
  (null, 'Färsk koriander', 'styck', 'produce', null),
  (null, 'Gräslök', 'styck', 'produce', null),
  (null, 'Färsk mynta', 'styck', 'produce', null),
  (null, 'Färsk timjan', 'styck', 'produce', null),
  (null, 'Färsk rosmarin', 'styck', 'produce', null),

  -- ---- protein -------------------------------------------------------------
  (null, 'Nötfärs', 'gram', 'protein', 'kott'),
  (null, 'Blandfärs', 'gram', 'protein', 'kott'),
  (null, 'Fläskfärs', 'gram', 'protein', 'kott'),
  (null, 'Kycklingfärs', 'gram', 'protein', 'kott'),
  (null, 'Högrev', 'gram', 'protein', 'kott'),
  (null, 'Ryggbiff', 'gram', 'protein', 'kott'),
  (null, 'Entrecôte', 'gram', 'protein', 'kott'),
  (null, 'Oxfilé', 'gram', 'protein', 'kott'),
  (null, 'Fläskkarré', 'gram', 'protein', 'kott'),
  (null, 'Fläskkotlett', 'gram', 'protein', 'kott'),
  (null, 'Fläskfilé', 'gram', 'protein', 'kott'),
  (null, 'Bacon', 'gram', 'protein', 'kott'),
  (null, 'Kokt skinka', 'gram', 'protein', 'kott'),
  (null, 'Kycklingfilé', 'gram', 'protein', 'kott'),
  (null, 'Kycklinglårfilé', 'gram', 'protein', 'kott'),
  (null, 'Hel kyckling', 'styck', 'protein', 'kott'),
  (null, 'Kalkonfärs', 'gram', 'protein', 'kott'),
  (null, 'Lammfärs', 'gram', 'protein', 'kott'),
  (null, 'Lammstek', 'gram', 'protein', 'kott'),
  (null, 'Falukorv', 'gram', 'protein', 'kott'),
  (null, 'Prinskorv', 'gram', 'protein', 'kott'),
  (null, 'Chorizo', 'gram', 'protein', 'kott'),
  (null, 'Salami', 'gram', 'protein', 'kott'),
  (null, 'Leverpastej', 'gram', 'protein', 'kott'),
  (null, 'Köttbullar', 'gram', 'protein', 'kott'),
  (null, 'Fläsklägg', 'gram', 'protein', 'kott'),
  -- Växtprotein ligger på samma hylla (category = butiksgruppering), men är
  -- neutralt. Det är hela skälet till att diet_tag inte kan härledas ur category.
  (null, 'Tofu', 'gram', 'protein', null),
  (null, 'Rökt tofu', 'gram', 'protein', null),
  (null, 'Tempeh', 'gram', 'protein', null),
  (null, 'Seitan', 'gram', 'protein', null),
  (null, 'Sojafärs', 'gram', 'protein', null),
  (null, 'Sojabitar', 'gram', 'protein', null),
  (null, 'Vegofärs', 'gram', 'protein', null),
  (null, 'Quornfärs', 'gram', 'protein', null),
  (null, 'Quornbitar', 'gram', 'protein', null),
  (null, 'Vegobullar', 'gram', 'protein', null),
  (null, 'Vegokorv', 'gram', 'protein', null),
  (null, 'Vegoburgare', 'styck', 'protein', null),
  (null, 'Falafel', 'gram', 'protein', null),
  (null, 'Hummus', 'gram', 'protein', null),

  -- ---- seafood -------------------------------------------------------------
  (null, 'Laxfilé', 'gram', 'seafood', 'fisk'),
  (null, 'Torskrygg', 'gram', 'seafood', 'fisk'),
  (null, 'Sej', 'gram', 'seafood', 'fisk'),
  (null, 'Kolja', 'gram', 'seafood', 'fisk'),
  (null, 'Rödspätta', 'gram', 'seafood', 'fisk'),
  (null, 'Räkor', 'gram', 'seafood', 'fisk'),
  (null, 'Handskalade räkor', 'gram', 'seafood', 'fisk'),
  (null, 'Blåmusslor', 'gram', 'seafood', 'fisk'),
  (null, 'Tonfisk på burk', 'gram', 'seafood', 'fisk'),
  (null, 'Makrill i tomatsås', 'gram', 'seafood', 'fisk'),
  (null, 'Sill', 'gram', 'seafood', 'fisk'),
  (null, 'Inlagd sill', 'gram', 'seafood', 'fisk'),
  (null, 'Gravad lax', 'gram', 'seafood', 'fisk'),
  (null, 'Rökt lax', 'gram', 'seafood', 'fisk'),
  (null, 'Fiskpinnar', 'styck', 'seafood', 'fisk'),
  (null, 'Pilgrimsmusslor', 'gram', 'seafood', 'fisk'),
  (null, 'Kräftor', 'gram', 'seafood', 'fisk'),
  (null, 'Kaviar', 'gram', 'seafood', 'fisk'),
  (null, 'Löjrom', 'gram', 'seafood', 'fisk'),

  -- ---- dairy ---------------------------------------------------------------
  -- Ägg och ost är neutrala: diet_class skiljer bara på kött och fisk, så
  -- lakto-ovo-frågor (löpe i parmesan m.m.) hör inte hemma i den här kolumnen.
  (null, 'Mellanmjölk', 'deciliter', 'dairy', null),
  (null, 'Lättmjölk', 'deciliter', 'dairy', null),
  (null, 'Standardmjölk', 'deciliter', 'dairy', null),
  (null, 'Laktosfri mjölk', 'deciliter', 'dairy', null),
  (null, 'Vispgrädde', 'deciliter', 'dairy', null),
  (null, 'Matlagningsgrädde', 'deciliter', 'dairy', null),
  (null, 'Crème fraîche', 'deciliter', 'dairy', null),
  (null, 'Gräddfil', 'deciliter', 'dairy', null),
  (null, 'Smör', 'gram', 'dairy', null),
  (null, 'Margarin', 'gram', 'dairy', null),
  (null, 'Hushållsost', 'gram', 'dairy', null),
  (null, 'Riven ost', 'gram', 'dairy', null),
  (null, 'Parmesan', 'gram', 'dairy', null),
  (null, 'Fetaost', 'gram', 'dairy', null),
  (null, 'Mozzarella', 'gram', 'dairy', null),
  (null, 'Halloumi', 'gram', 'dairy', null),
  (null, 'Keso', 'gram', 'dairy', null),
  (null, 'Kvarg', 'gram', 'dairy', null),
  (null, 'Naturell yoghurt', 'deciliter', 'dairy', null),
  (null, 'Grekisk yoghurt', 'deciliter', 'dairy', null),
  (null, 'Filmjölk', 'deciliter', 'dairy', null),
  (null, 'Ägg', 'styck', 'dairy', null),
  (null, 'Cheddar', 'gram', 'dairy', null),
  (null, 'Färskost', 'gram', 'dairy', null),
  (null, 'Smältost', 'gram', 'dairy', null),
  (null, 'Havremjölk', 'deciliter', 'dairy', null),
  (null, 'Sojamjölk', 'deciliter', 'dairy', null),
  (null, 'Mandelmjölk', 'deciliter', 'dairy', null),
  (null, 'Havregrädde', 'deciliter', 'dairy', null),

  -- ---- bakery --------------------------------------------------------------
  (null, 'Formfranska', 'styck', 'bakery', null),
  (null, 'Surdegsbröd', 'styck', 'bakery', null),
  (null, 'Rågbröd', 'styck', 'bakery', null),
  (null, 'Knäckebröd', 'styck', 'bakery', null),
  (null, 'Hamburgerbröd', 'styck', 'bakery', null),
  (null, 'Korvbröd', 'styck', 'bakery', null),
  (null, 'Tortillabröd', 'styck', 'bakery', null),
  (null, 'Pitabröd', 'styck', 'bakery', null),
  (null, 'Baguette', 'styck', 'bakery', null),
  (null, 'Ciabatta', 'styck', 'bakery', null),
  (null, 'Croissant', 'styck', 'bakery', null),
  (null, 'Kanelbulle', 'styck', 'bakery', null),
  (null, 'Rostbröd', 'styck', 'bakery', null),
  (null, 'Fullkornsbröd', 'styck', 'bakery', null),

  -- ---- grains --------------------------------------------------------------
  (null, 'Spaghetti', 'gram', 'grains', null),
  (null, 'Makaroner', 'gram', 'grains', null),
  (null, 'Penne', 'gram', 'grains', null),
  (null, 'Lasagneplattor', 'gram', 'grains', null),
  (null, 'Jasminris', 'gram', 'grains', null),
  (null, 'Basmatiris', 'gram', 'grains', null),
  (null, 'Råris', 'gram', 'grains', null),
  (null, 'Couscous', 'gram', 'grains', null),
  (null, 'Bulgur', 'gram', 'grains', null),
  (null, 'Quinoa', 'gram', 'grains', null),
  (null, 'Vetemjöl', 'deciliter', 'grains', null),
  (null, 'Dinkelmjöl', 'deciliter', 'grains', null),
  (null, 'Rågmjöl', 'deciliter', 'grains', null),
  (null, 'Potatismjöl', 'deciliter', 'grains', null),
  (null, 'Maizena', 'matsked', 'grains', null),
  (null, 'Strösocker', 'deciliter', 'grains', null),
  (null, 'Florsocker', 'deciliter', 'grains', null),
  (null, 'Farinsocker', 'deciliter', 'grains', null),
  (null, 'Ströbröd', 'deciliter', 'grains', null),
  (null, 'Havregryn', 'deciliter', 'grains', null),
  (null, 'Müsli', 'deciliter', 'grains', null),
  (null, 'Kokosflingor', 'deciliter', 'grains', null),
  (null, 'Kikärtor', 'gram', 'grains', null),
  (null, 'Svarta bönor', 'gram', 'grains', null),
  (null, 'Kidneybönor', 'gram', 'grains', null),
  (null, 'Vita bönor', 'gram', 'grains', null),
  (null, 'Röda linser', 'gram', 'grains', null),
  (null, 'Gröna linser', 'gram', 'grains', null),
  (null, 'Krossade tomater', 'gram', 'grains', null),
  (null, 'Passerade tomater', 'deciliter', 'grains', null),
  (null, 'Tomatpuré', 'matsked', 'grains', null),
  (null, 'Kokosmjölk', 'deciliter', 'grains', null),
  (null, 'Grönsaksbuljongtärning', 'styck', 'grains', null),
  -- De två raderna som gör hela kolumnen befogad: kött på torrvaruhyllan.
  (null, 'Hönsbuljongtärning', 'styck', 'grains', 'kott'),
  (null, 'Kalvfond', 'matsked', 'grains', 'kott'),
  (null, 'Honung', 'matsked', 'grains', null),
  (null, 'Sylt', 'matsked', 'grains', null),
  (null, 'Jordnötssmör', 'matsked', 'grains', null),
  (null, 'Olivolja', 'matsked', 'grains', null),
  (null, 'Rapsolja', 'matsked', 'grains', null),
  (null, 'Balsamvinäger', 'matsked', 'grains', null),
  (null, 'Soja', 'matsked', 'grains', null),
  (null, 'Dijonsenap', 'matsked', 'grains', null),
  (null, 'Ketchup', 'matsked', 'grains', null),
  (null, 'Majonnäs', 'matsked', 'grains', null),

  -- ---- fruit ---------------------------------------------------------------
  (null, 'Äpple', 'styck', 'fruit', null),
  (null, 'Banan', 'styck', 'fruit', null),
  (null, 'Apelsin', 'styck', 'fruit', null),
  (null, 'Citron', 'styck', 'fruit', null),
  (null, 'Lime', 'styck', 'fruit', null),
  (null, 'Päron', 'styck', 'fruit', null),
  (null, 'Vindruvor', 'gram', 'fruit', null),
  (null, 'Jordgubbar', 'gram', 'fruit', null),
  (null, 'Blåbär', 'gram', 'fruit', null),
  (null, 'Hallon', 'gram', 'fruit', null),
  (null, 'Mango', 'styck', 'fruit', null),
  (null, 'Ananas', 'styck', 'fruit', null),
  (null, 'Kiwi', 'styck', 'fruit', null),
  (null, 'Nektarin', 'styck', 'fruit', null),
  (null, 'Persika', 'styck', 'fruit', null),
  (null, 'Plommon', 'styck', 'fruit', null),
  (null, 'Cantaloupmelon', 'styck', 'fruit', null),
  (null, 'Vattenmelon', 'styck', 'fruit', null),
  (null, 'Granatäpple', 'styck', 'fruit', null),
  (null, 'Clementin', 'styck', 'fruit', null),
  (null, 'Björnbär', 'gram', 'fruit', null),
  (null, 'Russin', 'deciliter', 'fruit', null),
  (null, 'Torkade aprikoser', 'gram', 'fruit', null),
  (null, 'Dadlar', 'gram', 'fruit', null),

  -- ---- beverages -----------------------------------------------------------
  (null, 'Läsk', 'styck', 'beverages', null),
  (null, 'Cola', 'styck', 'beverages', null),
  (null, 'Saft', 'deciliter', 'beverages', null),
  (null, 'Apelsinjuice', 'deciliter', 'beverages', null),
  (null, 'Äppeljuice', 'deciliter', 'beverages', null),
  (null, 'Malet kaffe', 'gram', 'beverages', null),
  (null, 'Kaffebönor', 'gram', 'beverages', null),
  (null, 'Te', 'styck', 'beverages', null),
  (null, 'Mineralvatten', 'styck', 'beverages', null),
  (null, 'Kolsyrat vatten', 'styck', 'beverages', null),
  (null, 'Öl', 'styck', 'beverages', null),
  (null, 'Rödvin', 'deciliter', 'beverages', null),
  (null, 'Vitt vin', 'deciliter', 'beverages', null),

  -- ---- frozen --------------------------------------------------------------
  (null, 'Frysta ärtor', 'gram', 'frozen', null),
  (null, 'Frysta blåbär', 'gram', 'frozen', null),
  (null, 'Frysta hallon', 'gram', 'frozen', null),
  (null, 'Frysta wokgrönsaker', 'gram', 'frozen', null),
  (null, 'Frysta räkor', 'gram', 'frozen', 'fisk'),
  (null, 'Glass', 'deciliter', 'frozen', null),
  (null, 'Frysta klyftpotatis', 'gram', 'frozen', null),
  (null, 'Fryst bladspenat', 'gram', 'frozen', null),
  (null, 'Frysta majskorn', 'gram', 'frozen', null),
  -- Fryst pizza lämnas neutral: den kan vara vilket som helst, och att gissa
  -- "kott" hade gjort varje vegetarisk fredagspizza felmärkt utan förvarning.
  (null, 'Fryst pizza', 'styck', 'frozen', null),
  (null, 'Smördeg', 'styck', 'frozen', null),
  (null, 'Frysta jordgubbar', 'gram', 'frozen', null),

  -- ---- snacks --------------------------------------------------------------
  (null, 'Chips', 'gram', 'snacks', null),
  (null, 'Ostbågar', 'gram', 'snacks', null),
  (null, 'Popcorn', 'gram', 'snacks', null),
  (null, 'Saltnötter', 'gram', 'snacks', null),
  (null, 'Jordnötter', 'gram', 'snacks', null),
  (null, 'Cashewnötter', 'gram', 'snacks', null),
  (null, 'Mandlar', 'gram', 'snacks', null),
  (null, 'Choklad', 'gram', 'snacks', null),
  (null, 'Kex', 'gram', 'snacks', null),
  (null, 'Digestivekex', 'gram', 'snacks', null),
  (null, 'Godis', 'gram', 'snacks', null),
  (null, 'Lakrits', 'gram', 'snacks', null),

  -- ---- spices --------------------------------------------------------------
  (null, 'Salt', 'tesked', 'spices', null),
  (null, 'Flingsalt', 'tesked', 'spices', null),
  (null, 'Svartpeppar', 'kryddmatt', 'spices', null),
  (null, 'Vitpeppar', 'kryddmatt', 'spices', null),
  (null, 'Paprikapulver', 'tesked', 'spices', null),
  (null, 'Rökt paprikapulver', 'tesked', 'spices', null),
  (null, 'Chilipulver', 'tesked', 'spices', null),
  (null, 'Spiskummin', 'tesked', 'spices', null),
  (null, 'Curry', 'tesked', 'spices', null),
  (null, 'Kanel', 'tesked', 'spices', null),
  (null, 'Malen kardemumma', 'tesked', 'spices', null),
  (null, 'Muskotnöt', 'kryddmatt', 'spices', null),
  (null, 'Malen ingefära', 'tesked', 'spices', null),
  (null, 'Gurkmeja', 'tesked', 'spices', null),
  (null, 'Torkad oregano', 'tesked', 'spices', null),
  (null, 'Torkad basilika', 'tesked', 'spices', null),
  (null, 'Torkad timjan', 'tesked', 'spices', null),
  (null, 'Torkad rosmarin', 'tesked', 'spices', null),
  (null, 'Lagerblad', 'styck', 'spices', null),
  (null, 'Vitlökspulver', 'tesked', 'spices', null),
  (null, 'Lökpulver', 'tesked', 'spices', null),
  (null, 'Cayennepeppar', 'kryddmatt', 'spices', null),
  (null, 'Chiliflakes', 'tesked', 'spices', null),
  (null, 'Sesamfrön', 'matsked', 'spices', null),
  (null, 'Bakpulver', 'tesked', 'spices', null),
  (null, 'Bikarbonat', 'tesked', 'spices', null),
  (null, 'Vaniljsocker', 'matsked', 'spices', null),
  (null, 'Vaniljstång', 'styck', 'spices', null),
  (null, 'Kanelstång', 'styck', 'spices', null),
  (null, 'Saffran', 'gram', 'spices', null),
  (null, 'Fänkålsfrön', 'tesked', 'spices', null),
  (null, 'Senapsfrön', 'tesked', 'spices', null),
  (null, 'Korianderfrön', 'tesked', 'spices', null),
  (null, 'Torkad dill', 'tesked', 'spices', null),
  (null, 'Herbes de Provence', 'tesked', 'spices', null),

  -- ---- household -----------------------------------------------------------
  (null, 'Toalettpapper', 'styck', 'household', null),
  (null, 'Hushållspapper', 'styck', 'household', null),
  (null, 'Diskmedel', 'styck', 'household', null),
  (null, 'Disktrasa', 'styck', 'household', null),
  (null, 'Tvättmedel', 'styck', 'household', null),
  (null, 'Soppåsar', 'styck', 'household', null),
  (null, 'Plastfolie', 'styck', 'household', null),
  (null, 'Aluminiumfolie', 'styck', 'household', null),
  (null, 'Bakplåtspapper', 'styck', 'household', null),
  (null, 'Tandkräm', 'styck', 'household', null),
  (null, 'Tvål', 'styck', 'household', null),
  (null, 'Schampo', 'styck', 'household', null),
  (null, 'Servetter', 'styck', 'household', null),
  (null, 'Kaffefilter', 'styck', 'household', null),
  (null, 'Tändstickor', 'styck', 'household', null),
  (null, 'Ljus', 'styck', 'household', null),
  (null, 'Batterier', 'styck', 'household', null),
  (null, 'Rengöringsmedel', 'styck', 'household', null)
on conflict (home_id, lower(trim(name))) do update
  set diet_tag = excluded.diet_tag;

-- Kontroll: 314 rader – 28 kött, 20 fisk, 266 neutrala.
--   select coalesce(diet_tag::text, 'neutral') as tag, count(*)
--   from ingredients where home_id is null
--   group by 1 order by 2 desc;
